spring:
  application:
    name: ecommerce_app
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=full-stack-ecommerce
    username: postgres
    password: ecommerce
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: false
    # hibernate:
      # ddl-auto: create-drop

logging:
  level:
    root: warn

server:
  port: 8081 
